from __future__ import annotations
import argparse
import re
import struct
from pathlib import Path

INT_OFFSET = 65536
GACHA_ITEM_LIST_LENGTH = 84

LINE_RE = re.compile(r"^\s*0x[0-9A-Fa-f]+\s+(?P<name>\S+)\s+(?P<typ>\S+)\s+=\s+(?P<value>.*)$")


def parse_value(typ: str, text: str):
    text = text.strip()
    if typ == "bool":
        return text.lower() in ("true", "1", "yes", "true")
    if typ in ("int", "long", "BigInteger", "uint32"):
        return int(text)
    if typ == "double":
        return float(text)
    raise ValueError(f"Unknown type: {typ}")


def load_dump(path: Path) -> dict[str, tuple[str, object]]:
    fields: dict[str, tuple[str, object]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        m = LINE_RE.match(line)
        if not m:
            continue
        name = m.group("name")
        typ = m.group("typ")
        value = parse_value(typ, m.group("value"))
        fields[name] = (typ, value)
    if not fields:
        raise RuntimeError("No fields found in dump. Is this a save_dump.txt generated by the dumper?")
    return fields


class Writer:
    def __init__(self, fields: dict[str, tuple[str, object]]):
        self.fields = fields
        self.out = bytearray()

    def get(self, name: str, expected_type: str):
        if name not in self.fields:
            raise KeyError(f"Missing field in dump: {name}")
        typ, value = self.fields[name]
        if typ != expected_type:
            raise TypeError(f"Field {name}: expected {expected_type}, found in dump {typ}")
        return value

    def uint32_raw(self, name: str):
        self.out += struct.pack("<I", int(self.get(name, "uint32")) & 0xFFFFFFFF)

    def int32(self, name: str):
        v = int(self.get(name, "int")) + INT_OFFSET
        self.out += struct.pack("<I", v & 0xFFFFFFFF)

    def int64(self, name: str):
        v = int(self.get(name, "long")) + INT_OFFSET
        self.out += struct.pack("<Q", v & 0xFFFFFFFFFFFFFFFF)

    def boolean(self, name: str):
        self.out.append(1 if bool(self.get(name, "bool")) else 0)

    def double(self, name: str):
        self.out += struct.pack("<d", float(self.get(name, "double")))

    def bigint(self, name: str):
        v = int(self.get(name, "BigInteger"))
        b = bigint_to_dotnet_bytes(v)
        self.out += struct.pack("<I", len(b))
        self.out += b

    def arr(self, base: str, count: int, fn):
        for i in range(count):
            fn(f"{base}[{i}]")


def bigint_to_dotnet_bytes(v: int) -> bytes:
    """Minimal little-endian two's-complement bytes compatible with .NET BigInteger(byte[])."""
    if v == 0:
        return b"\x00"
    if v > 0:
        n = (v.bit_length() + 7) // 8
        b = v.to_bytes(n, "little", signed=False)
        # Add positive sign byte if the highest bit would look negative to BigInteger(byte[]).
        if b[-1] & 0x80:
            b += b"\x00"
        return b
    # negative values are unlikely here, but handle them anyway
    n = max(1, (v.bit_length() + 8) // 8)
    while True:
        try:
            b = v.to_bytes(n, "little", signed=True)
        except OverflowError:
            n += 1
            continue
        # ensure it is minimal while preserving sign
        if n > 1:
            test = int.from_bytes(b[:-1], "little", signed=True)
            if test == v and (b[-2] & 0x80):
                n -= 1
                continue
        return b


def build_sav(fields: dict[str, tuple[str, object]]) -> bytes:
    w = Writer(fields)
    w.uint32_raw("version")
    w.arr("currencyArray", 6, w.bigint)
    w.arr("secretCurrencyArray", 6, w.bigint)
    w.arr("upgradeLevels", 232, w.int64)
    w.arr("secretShopLevels", 20, w.int64)
    w.int64("magicRank")
    w.bigint("magicXP")
    w.arr("magicStats", 9, w.int64)
    w.double("trialMulti")
    w.int64("shadowRealmSkeletons")
    w.arr("jackpotGot", 5, w.boolean)
    w.arr("bestTicketWin", 5, w.bigint)
    w.arr("ticketLevel", 5, w.int64)
    w.arr("ticketXp", 5, w.bigint)
    w.arr("ticketStock", 5, w.int32)
    w.int32("bestHand")
    w.arr("pachiPinLevels", 136, w.int64)
    w.arr("pachiPinXp", 136, w.bigint)
    w.arr("costReductionAccumulation", 5, w.double)
    w.int32("highestSushiAchieved")
    w.arr("sushiBoardType", 102, w.int32)
    w.arr("sushiType", 102, w.int32)
    w.arr("shakerUses", 4, w.int64)
    w.arr("perfecto", 70, w.boolean)
    w.arr("sushiLevel", 70, w.int64)
    w.arr("sushiXP", 70, w.int64)
    w.double("greenShakeMulti")
    w.arr("wheelWin", 2, w.boolean)
    w.int64("wheelSpinCount")
    w.arr("miniGameMulti", 3, w.double)
    w.bigint("pachiBalls")
    w.bigint("fuel")
    w.bigint("tokens")
    w.arr("tutorialCounters", 21, w.int32)
    w.int32("bottle")
    w.double("janitorMulti")
    w.arr("gumballLevels", 8, w.int64)
    w.int32("unlockedWorlds")
    w.boolean("startedGame")
    w.boolean("completedGame")
    w.arr("bodyguardSummoned", 5, w.boolean)
    w.boolean("sushiSaved")
    w.arr("gachaItems", GACHA_ITEM_LIST_LENGTH, w.int32)
    w.int32("wellRestedMarks")
    w.int32("pachiLeverState")
    w.boolean("isLethalMode")
    w.int64("NGPlus")
    w.int64("frameTimer")
    w.double("scratchSize")
    w.int32("wheelPitySpins")
    w.boolean("autoscratchOn")
    w.int64("zenithGemRank")
    w.int64("zenithGemCount")
    w.arr("zenithLevels", 40, w.int32)
    w.int32("zenithCooldown")
    return bytes(w.out)


def main():
    ap = argparse.ArgumentParser(description="Build a Fortune Mill .sav file from an edited save_dump.txt")
    ap.add_argument("dump", nargs="?", default="save_dump.txt", help="Input dump file (default: save_dump.txt)")
    ap.add_argument("out", nargs="?", default="save_dump.sav", help="Output save file (default: save_dump.sav)")
    args = ap.parse_args()

    dump_path = Path(args.dump)
    out_path = Path(args.out)
    fields = load_dump(dump_path)
    data = build_sav(fields)
    out_path.write_bytes(data)
    print(f"Written: {out_path.resolve()}")
    print(f"Size: {len(data)} Bytes")
    print("To test: close the game, back up the original save_game.sav, then copy this file as save_game.sav.")


if __name__ == "__main__":
    main()
